name: Release Publish

on:
  pull_request:
    types:
      - closed
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event.pull_request.merged == true &&
        startsWith(github.event.pull_request.title, 'chore(master): release')
      )

    runs-on: ubuntu-latest

    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
