name: Release
on:
  schedule:
    - cron: '0 17 * * 5'
  push:
    branches: [master]
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    if: github.repository == 'Fotetsa/hullbay'
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json