name: Release

on:
  schedule:
    # Every Friday at 17:00 Cameroon time (UTC+1)
    - cron: '0 16 * * 5'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    if: github.repository == 'Fotetsa/hullbay'

    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
